server:
  port: 8001
spring:
  application:
    name: CloudVault
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.198.242.154:3306/CloudVault?useSSL=false&serverTimezone=UTC
    username: root
    password: 'Chad@20021231'
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  redis:
    host: 121.40.204.51
    port: 6379
    #    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

mybatis-plus:
  type-aliases-package: org.chad.cloudvault.domain.po
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted # 配置逻辑删除字段
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
minio:
  endpoint: http://116.198.242.154:9090
  accessKey: minio
  secretKey: minio123
  bucketName: cloudvault
file:
  init-size: 5368709120
  shard-size: 10485760
wechat:
  app-id: wxbba59da171843ee4
  app-secret: 55670f9a2bb46c3428b248c3cb761e06
  domain: http://4trzx7.natappfree.cc
  redirect-uri: /user/wechatLogin
